all:
	cc -o testDataStructures testDataStructures.c

test:
	cc -o testDataStructures testDataStructures.c
	cc -o testAdjacencyList testAdjacencyList.c
	cc -o testBreadthFirstSearch testBreadthFirstSearch.c

	./testAdjacencyList
	./testDataStructures
	./testBreadthFirstSearch

clean:
	rm adjacencyListTest
