all: 
	cc -o testFordFulkerson testFordFulkerson.c

test:
	cc -o testDataStructures testDataStructures.c
	cc -o testAdjacencyList testAdjacencyList.c
	cc -o testBreadthFirstSearch testBreadthFirstSearch.c
	cc -o testFordFulkerson testFordFulkerson.c

	./testAdjacencyList
	./testDataStructures
	./testBreadthFirstSearch

clean:
	-rm testDataStructures
	-rm testAdjacencyList
	-rm testBreadthFirstSearch
